# Generated by Django 4.0.3 on 2022-04-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('site_id', models.TextField()),
                ('title', models.TextField()),
                ('content', models.TextField(blank=True, null=True)),
                ('imgs', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('prix', models.FloatField(blank=True, null=True)),
                ('surface', models.FloatField(blank=True, null=True)),
                ('url', models.TextField(blank=True)),
                ('phones', models.TextField(blank=True, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('domain', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField()),
                ('score', models.IntegerField(default=0)),
                ('is_relevant', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('site_id', 'domain')},
            },
        ),
    ]
