# Generated by Django 4.0.3 on 2022-04-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portail', '0004_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_date', models.DateTimeField()),
                ('last_date', models.DateTimeField()),
                ('url', models.TextField(blank=True, null=True)),
                ('classe', models.TextField(blank=True, null=True)),
                ('domain', models.TextField(blank=True, null=True)),
                ('content', models.TextField()),
                ('exception_type', models.CharField(max_length=128)),
                ('checksum', models.TextField()),
            ],
            options={
                'unique_together': {('classe', 'checksum')},
            },
        ),
    ]
